#!/bin/sh

echo 'start remove docker baidunetdisk container.' >> "${SYNOPKG_PKGDEST}/package/logs/output.log"

container_id=$(cat "${SYNOPKG_PKGDEST}/package/cid")
container_name=$(docker ps --filter "id=${container_id}" --format "{{.Names}}")

docker stop -t 0 $container_id 2>>"${SYNOPKG_PKGDEST}/package/logs/output.log"
docker rm -f $container_id >> "${SYNOPKG_PKGDEST}/package/logs/output.log" 2>&1
ret=$?

if [ -f "/usr/local/etc/services.d/docker_${container_name}.sc" ]; then
    rm -f "/usr/local/etc/services.d/docker_${container_name}.sc"
fi

exit $ret
