#!/bin/sh

case $1 in
    start)
        ### Start this package.
        exit 0
    ;;
    stop)
        ### Stop this package.
        exit 0
    ;;
    log)
        /bin/curl -v 127.0.0.1:6900 -o /dev/null
    ;;
    status)
        /bin/curl -s 127.0.0.1:6900 -o /dev/null
    ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 0
    ;;
esac

